name: unit-tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  gtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build code with CMake
        run: |
          cmake -B ${{ github.workspace }}/build
          cmake --build ${{ github.workspace }}/build --config Release

      - name: Run GTest
        run: ctest -C ${{env.BUILD_TYPE}}
        working-directory: ${{ github.workspace }}/build//tests