name: unit-tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  gtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build code with CMake
        run: |
          cmake -B ${{ github.workspace }}/build
          cmake --build ${{ github.workspace }}/build --config Debug

      - name: Run tests
        run: |
          sh ${{ github.workspace }}/tests/run_test.sh